project:
  type: website
  output-dir: docs

lang: en

execute:
  freeze: false
  cache: true

format:
  html:
    theme:
      light: flatly
      dark:  darkly
    callout-appearance: simple
    css: assets/styles.css
    toc: true
    smooth-scroll: true
    highlight-style: atom-one
    number-sections: true
    number-depth: 3
    pagetitle: "{{< var meta.title >}}"

website:
  repo-url: https://github.com/jtvandijk/SA-TIED
  repo-actions: [issue]
  page-navigation: true
  page-footer:
    center: "Course material by [Justin van Dijk](https://www.mappingdutchman.com). Available under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)."
  search:
    location: sidebar
    type: overlay
  sidebar:
    style: floating
    collapse-level: 2
    logo: assets/logo.svg
    tools:
      - icon: github
        href: https://github.com/jtvandijk/SA-TIED
    contents:
      - section: "Workshop overview"
        contents:
          text: "Welcome"
          file: 00-index.qmd
      - section: "Spatial Data"
        contents:
          - 01-getting-started.qmd
          - 02-mapping-data.qmd
      - section: "Spatial Models"
        contents:
          - 04-spatial-autocorrelation.qmd
          - 05-spatial-models.qmd
          
editor: source